# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23921c63c8da2ab18b443ca243f142c67c7a5d8c7b5edaee892d80bfd2ff88ec2400c43ecac1e017527c7c7b088c4acf3d33646ae9756aafe8069492831ac692

test:
  secret_key_base: 13efc27c9cefb40bcadc7a80a262565beda3202502095d91fad2269072e9d59a406e1b6c2fc413bff5a9da7265211444abe4d616bcfc1c8cdb18e5ef9378da67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
